# Generated by Django 3.0.5 on 2020-05-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200526_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
